package.json

chore(package): update babel-cli to version 6.5.0

---

lib/get/get-full-source-space.js

This pull request is extending the functionality of the export-tool and adding 2 more entities to export, webhooks and editorInterface.

Add webhooks and editorInterfaces

---

lib/push/push-to-space.js
test/push/push-to-space-test.js

This is an addition to the batch lib to be able to sync editor interfaces across spaces

feat(contentful-import): Add support for importing editor Interfaces

---

lib/get/get-full-source-space.js

The idea is to make the limit sent in the query configurable 
More Info : https://github.com/contentful/contentful-batch-libs/issues/72

feat(get-full-source-space): Make limit configurable

---

lib/push/push-to-space.js
lib/transform/transform-space.js
lib/transform/transformers.js
test/push/push-to-space-test.js
test/runner

Add support for importing webhooks

feat(push-to-space): Add support for importing webhooks

---

lib/push/push-to-space.js

This PR addresses #83 along with some minor code style adjustments. Let me know if you need any further changes.

Fix drafts detection in pushToSpace

---

lib/push/creation.js

Some minor things I thought would be worthwhile in terms of code cleanup. WDYT?

Minor code style improvements

---

lib/utils/create-clients.js

killing `rateLimit` and `rateLimitPriod` with 🔥

chore(createClients): Remove unused code

---

lib/get/get-outdated-destination-content.js
test/get/get-outdated-destination-content-test.js

fix(outdated content): apply limit to batched id query

---

lib/get/get-full-source-space.js
package.json

This pull requests currently only contains changes related to https://github.com/contentful/contentful-export/pull/49
More commits will follow.

task-listing for import & export

---

lib/transform/transform-space.js

This is a first attempt at addressing #87.

Enable async entity transforms

---

lib/transform/transform-space.js

Reverts contentful/contentful-batch-libs#88

Revert "Enable async entity transforms"

---

lib/push/publishing.js
test/push/publishing-test.js

fixes https://github.com/contentful/contentful-import/issues/49

fix(publishing): queue does now abort automatically

---

package.json

Bump contentful-management version to fix the proxy issue

fix(axios): fix proxy

---

lib/push/creation.js
lib/push/push-to-space.js
lib/utils/logging.js
test/push/push-to-space-test.js

This is the actual branch which fixes the draft asset processing bug + integrates the push to space function with listr for proper display.

implement listr for push to space

---

lib/get/get-full-source-space.js
lib/push/publishing.js
lib/push/push-to-space.js
test/push/push-to-space-test.js

fix: Handle archived entities

---

lib/push/push-to-space.js

closes contentful/contentful-import#74

fix: extra check for null entity

---

.circleci/config.yml
.gitignore
.travis.yml

Add a Circle CI configuration and remove the old travis CI configuration in order to ensure a working CI/CD pipeline.

Feat(ci): Add Circle CI

---

babel.config.json
lib/add-sequence-header.js
package-lock.json
package.json
test/add-sequence-header.test.js

Add helper function which adds a sequence header to an existing headers object.
Bump babel from version 6 to 7.

feat(headers): Add sequence header

---

test/listr.test.js

chore(listr): remove unneeded comments

---

package-lock.json
package.json
types.d.ts

Adds typescript types to this package.
I have tested these locally by using the `npm link` command and using the new types in the contentful-export library.

Add types.d.ts file

---

.github/dependabot.yml
.github/workflows/dependabot-approve-and-request-merge.yml

Add dependabot and auto-merge workflow.

chore: add dependabot [NONE]

---

.github/CODEOWNERS
package-lock.json

chore: audit deps and unown package files to allow dependabot to work properly [EXT-5894]
