contentful/contentful-batch-libs

lib/get/get-full-source-space.js

This change is adding the support for exporting entries including drafts if the deliveryClient is provided

feat(get-sull-space): Export drafts when deliveryClient is provided

---

lib/push/creation.js

I ran into some problems when `details` was not present on `error`. In other places details are obtained using lodash's `get`, to circumvent this problem. Adopted the same behavior here.

Obtain errors safely in handleEntryCreationErrors

---

lib/transform/transform-space.js

I'm trying to migrate one space to another. This migration will require quite a lot of transformations. Since I plan to use this project as a submodule without modifying any of the existing code, I wanted a way to pass in the transformers for my content as a parameter.
What do you think?

Allow default transformers overwrite

---

lib/transform/transformers.js

This PR fixes the error when trying to import an asset with `uploadFrom` and `upload` fields at the same time. The fix is a workaround until the backend fixes the payload issue

fix(transforms): remove extra uploadFrom

---

lib/transform/transformers.js

This PR is a workaround to avoid breaking the import process when importing webhooks with credential which is not possible since the exported payload will contain only the username and not the password due to security measures in the CMA API. The CMA will return a validation error which we can avoid by removing the username field and the user can refill the credential again once everything is imported

fix(webhooks): Workaround webhooks with credentials issue

---

lib/index.js
lib/push/index.js
lib/transform/index.js

You guys broke pretty much all your exports with 76a790884a4c0da6ab9b5a7d6a08af205db3eca8 😳
A lot of the modules in this project don't have a default export and yet you re-exported a default export from them. This caused the members of the main module to be `undefined` after the babel transpilation process.
Took me pretty much all day to figure out it was the library and not some weird node dependency quirk on my system ಠ_ಠ
How did this get into master? 😞

Fix module exports across project

---

README.md

Since the space-sync-tool is deprecated and this repo is now used by the import & export tool, we should change the readme file accordingly.

docs(README): remove mention of space-sync-tool

---

lib/get/get-full-source-space.js

Some old content types do not have a editor interface. Also unpublished ones do not have.
This fixes https://github.com/contentful/contentful-import/issues/35

add editor interface filter for old content types

---

lib/get/get-full-source-space.js

as reported by @stupchiy, another little 🐛  we introduced in the refactoring 😞

fix(flags): fix --includeDrafts flag

---

lib/push/push-to-space.js

Previously webhooks were imported before importing entries and assets which was not a smart ordering. Since webhooks could be triggered on every entry/asset publishing and if the webhook endpoint is triggering another api request which could affect rate limit.
This PR fixes that by making webhooks import last thing.

fix(push-to-space): Import webhooks last

---

lib/push/creation.js

This PR adds concurrency when creating entries, 😱  concurrency was unlimited before which is not good for rate limiting
👇  tested in with contentful-import and all is fine

fix(creation): Add concurrency for entris creation

---

lib/push/publishing.js
test/push/publishing-test.js

Fixes:
* Publishing of linked entities by re-queueing unresolvable ones
* https://github.com/contentful/contentful-import/issues/7
* might fix (some?) issues in here https://github.com/contentful/contentful-import/issues/36
* Some other users problems
Does not fix:
* Circular dependencies

add publishing queue to retry unresolvable publish actions

---

lib/get/get-full-source-space.js

To make sure that the filter function works fine we make sure to return an actual boolean value

force the value to be boolean

---

.babelrc
.gitignore
lib/push/creation.js
test/push/creation-test.js

when you provide a content-file that does not contain an entry id, the import tool still uses `space.createEntryWithId` which results in entry created with id `undefined`

fix(creation): Use createEntry when id is not provided

---

lib/get/get-outdated-destination-content.js
test/get/get-outdated-destination-content-test.js

instead of passing some flags and id's, I now pass the whole `sourceResponse` (aka the content file content), use batchedIdQueries on all entity types and generate the id's on the fly when it is needed. Will also save a little performance.

fix(existing-content): paginate in the existing content check

---

lib/push/assets.js

Hi, 
I'm using `contentful-import@next` with `contentful-batch-libs@next` and I have occasionally errors with assets that are `null` during the `processAssets` task.
So I come up with a simple solution: checking if an asset exists before calling `processForAllLocales()` method.
Vincenzo

fix: check if an asset exists before processing

---

lib/get/get-full-source-space.js
lib/push/push-to-space.js
lib/utils/listr.js
lib/utils/logging.js
package.json
test/utils/listr-test.js

I guess this is the least effort to fix the display issue when a task itself fails and returns an error from the SDK.
Workarounding here the JSON.stringified error message here till we have a SDK error format which is easy to detect and work with.

fix(errors): failing tasks now use human readable error format

---

.eslintrc.js
package.json
test/push/creation.test.js
test/push/publishing.test.js

downgrade to jest 21 to make it work on node 4 till we can switch to node 6
I have no idea why this worked for node 4 for the last PR. 🤷‍♂️

test(jest): use jest 21 for node 4

---

lib/transform/transformers.js
test/transform/transformers.test.js

This PR fixes the asset transformer to make sure the protocol of the asset url is set correctly without double `https:`

test(transformer): remove duplicate protocol

---

.gitignore
package-lock.json
package.json

Updated `https-proxy-agent` dependency due to [vulnerability](https://www.npmjs.com/advisories/1184) and added `package-lock.json` file.

fix(dependency): Update https-proxy-agent dependency

---

package-lock.json
package.json

Downgrade https-proxy-agent because structure* of newer versions is incompatible with current contentful-export requirements.
* The options field of the resulting HttpsAgent object is not populated with host and port fields.

fix(dep): downgrade https-proxy-agent for compatibility

---

lib/proxy.js
test/proxy.test.js

Added protocol property to be passed to the https-proxy-agent since this is in line with [what the agent expects](https://github.com/TooTallNate/node-https-proxy-agent/blob/c30a9dc75a272591a80b9b4acef1496f80824f88/src/agent.ts#L50) for TLS upgrade.

feature(proxy): add protocol to https-agent [SDK-2056]

---

lib/get-entity-name.js
lib/logging.js
lib/proxy.js
package-lock.json
package.json
test/mocks/index.js

This PR attempts to remove `lodash` wherever possible to reduce package bloat:
- `lodash/get` can be replaced with optional chaining (`?.`) syntax
- `lodash/isObject` is used on a `JSON.parse` object meaning we only need to check `data && typeof data === 'object'` to get the same behaviour
- `lodash/toInteger` is not the same as `parseInt`. However, the `node:url.URL` class already does some validation checks on the `port` variable. So this is a safe conversion from string to integer (`number`)
- `lodash/assign` is equivalent to `Object.assign`
- `lodash/cloneDeep` is not so easy to replace. Instead opting to replace with `lodash.clonedeep` module, which individually has  packages lodash's `cloneDeep` functionality (reducing package bloat)

chore(deps): remove lodash

---

lib/add-sequence-header.js
lib/index.js
test/add-sequence-header.test.js
test/get-entity-name.test.js
test/listr.test.js

Currently consumers of this package are required to know the internal structure to import required modules. This PR introduces an `index.js` file to alleviate this problem.
Previous import syntax:
```js
import { wrapTask } from 'contentful-batch-libs/dist/listr';
import { logEmitter } from 'contentful-batch-libs/dist/logging';
```
New syntax:
```js
import { wrapTask, logEmitter } from 'contentful-batch-libs';
```
This PR introduces no breaking changes in itself. However, I have left some todo's to suggest next major release to remove `export default` in favour of named exports.
Additionally I do not believe every function in this package needs to be exported from this new `index.js` file. I have only included exports that are used in either the `contentful-export` or `contentful-import` …

feat(index.js): add single entrypoint

---

lib/logging.js
package-lock.json
package.json
test/logging.test.js

Now that moment.js is not being used in either contentful-import or contentful-export, it is safe to replace this now with date-fns. See https://github.com/contentful/contentful-import/pull/602 for more info

chore(deps): replace moment with date-fns

---

lib/logging.js
test/logging.test.js

While replacing moment.js with date-fns, it was assumed the tests were correct. Unfortunately this is not the case: 
- unit tests assumed timestamps were of type `number`
- users are converting timestamps to a string, commonly `new Date().toJson()`
This will address the following downstream reported issue: https://github.com/contentful/contentful-cli/issues/1507

fix(date-fns): fix invalid time error

---

test/listr.test.js
test/logging.test.js
test/proxy.test.js

- Refactor tests to use async/await syntax
- Remove custom test expect messages - the jest API does not support this (found this whilst trying to refactor to TS)
- General code clean up

chore(tests): tidy tests to be @types/jest compliant

---

lib/logging.js
test/logging.test.js

Found this issue when migration the file to TS, thought it would be worthwhile to separate it into its own PR. The problem is this line:
```js
const errorsCount = errorLog.filter((error) => Object.prototype.hasOwnProperty.call(error, 'warning')).length
```
As you can see it is counting the number of warnings (not errors).
In fixing this PR, I modified this code to use the `Array.prototype.reduce` function to prevent iterating over the `errorLog` array twice.

fix(logging): fix reported errors count

---

.github/dependabot.yml
lib/proxy.js
package-lock.json
package.json
test/proxy.test.js

After [bumping](https://github.com/contentful/contentful-batch-libs/pull/199) `https-proxy-agent`, the usage broke due to a [changed](https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/CHANGELOG.md#600) interface. This change aligns with the new format. To ensure such insecure changes do not end up on `master` again, the branch protection rule has been restricted with the required checks.
Additionally we pinned dependencies with ESM only bundles.

fix: https-proxy-agent usage after version bump [NONE]

---

.github/dependabot.yml
lib/logging.js
package-lock.json
package.json
test/logging.test.js
types.d.ts

- `bfj` has been archived repository for some time now
- Its use has been limited as `writeErrorLogFile` loads the `errorLog` completely into memory, transforms it, then writes it to a log file using `bfj`. Obviously if the data is so large that it requires `bfj`, then loading it completely into to memory would more than likely crash the process.
- `bfj` does not have `@types/bfj` available.

feat: Remove BFJ for async streaming

---

lib/logging.ts

- Modifies the `log` parameter to be optional.
- Returns the `log` value (whether passed-in or instantiated)
```js
const log = []
const options = parseOptions(params)
const listrOptions = createListrOptions(options)
// Setup custom error listener to store errors for later
setupLogging(log)
```
New behaviour:
```js
// Setup custom error listener to store errors for later
const log = setupLogging()
const options = parseOptions(params)
const listrOptions = createListrOptions(options)
```
```js
const log = []
const options = parseOptions(params)
const listrOptions = createListrOptions(options)
const requestQueue = new PQueue({
interval: ONE_SECOND,
intervalCap: options.rateLimit,
carryoverConcurrencyCount: true
})
// Setup custom log listener to store log messages for later
setupLogging(log) …
```

feat: Improve 'setupLogging' to instantiate a log array if none is provided

---

lib/get-entity-name.ts

Turns out that the way we use this function doesn't always guaranty an input object. to not break the downstream consumers, we also allow calling this function without input param.

fix: get entity name function optional param [NONE]
